/* 4.6.0 a 4.7.0 */
UPDATE CORE_PARAMETRO_CONFIGURACION SET VALOR='4.6.0' WHERE NOMBRE='version.datamodel.scsp';   

/* 4.7.0 a 4.8.0 */
UPDATE CORE_PARAMETRO_CONFIGURACION SET VALOR='4.8.0' WHERE NOMBRE='version.datamodel.scsp';  
ALTER TABLE CORE_EMISOR_CERTIFICADO ADD FECHAALTA TIMESTAMP (6);
UPDATE CORE_EMISOR_CERTIFICADO SET FECHAALTA = SYSDATE  WHERE FECHAALTA IS NULL;

/* 4.8.0 a 4.16.0 */
ALTER TABLE CORE_TRANSMISION MODIFY ESTADO VARCHAR2(10);
UPDATE CORE_PARAMETRO_CONFIGURACION SET VALOR='4.16.0' where NOMBRE='version.datamodel.scsp'; 

/* 4.16.0 a 4.19.0 */
CREATE INDEX CORE_SERVICIO_INDEX_EMISOR  ON CORE_SERVICIO (EMISOR);