/* 4.2.0 a 4.3.0 */
UPDATE CORE_PARAMETRO_CONFIGURACION SET VALOR='4.3.0' WHERE NOMBRE='version.datamodel.scsp';   
UPDATE CORE_SERVICIO SET XPATHCODIGOERROR='//*[local-name()=''CodigoEstado'']', XPATHLITERALERROR= '//*[local-name()=''LiteralError'']', XPATHCODIGOERRORSECUNDARIO='//*[local-name()=''CodigoEstadoSecundario'']' where codcertificado='Q2827002CINSS002';
UPDATE CORE_SERVICIO SET XPATHCODIGOERROR='//*[local-name()=''CodRet'']' ,XPATHLITERALERROR='//*[local-name()=''DescripcionError'']' where CODCERTIFICADO='HTNIAE';
UPDATE CORE_SERVICIO SET XPATHCODIGOERROR='//*[local-name()=''Codigo'']', XPATHLITERALERROR='//*[local-name()=''Descripcion'']' where CODCERTIFICADO='S2800665HFTF0003';
UPDATE CORE_SERVICIO SET XPATHCODIGOERROR='//*[local-name()=''Codigo'']', XPATHLITERALERROR='//*[local-name()=''Descripcion'']' where CODCERTIFICADO='S2800665HFTF0002';
UPDATE CORE_SERVICIO SET XPATHCODIGOERROR='//*[local-name()=''Codigo'']', XPATHLITERALERROR='//*[local-name()=''Descripcion'']' where CODCERTIFICADO='S2800665HFTF0001';
UPDATE CORE_SERVICIO SET XPATHLITERALERROR='//*[local-name()=''Literal'']' where CODCERTIFICADO='SVDMATUNIVWS01';

UPDATE CORE_SERVICIO SET  XPATHCODIGOERRORSECUNDARIO='//*[local-name()=''CodigoEstadoSecundario'']'  WHERE CODCERTIFICADO='SVDPERMEXWS01';
UPDATE CORE_SERVICIO SET  XPATHCODIGOERRORSECUNDARIO='//*[local-name()=''CodigoEstadoSecundario'']'  WHERE CODCERTIFICADO='SVDSCDWS01';
UPDATE CORE_SERVICIO SET  XPATHCODIGOERRORSECUNDARIO='//*[local-name()=''CodigoEstadoSecundario'']'  WHERE CODCERTIFICADO='SVDDGPCIWS02';
UPDATE CORE_SERVICIO SET  XPATHCODIGOERRORSECUNDARIO='//*[local-name()=''CodigoEstadoSecundario'']'  WHERE CODCERTIFICADO='SVDDGPVIWS02';
UPDATE CORE_SERVICIO SET  XPATHCODIGOERRORSECUNDARIO='//*[local-name()=''CodigoEstadoSecundario'']'  WHERE CODCERTIFICADO='SVDSECOPA01WS01';
UPDATE CORE_SERVICIO SET  XPATHCODIGOERRORSECUNDARIO='//*[local-name()=''CodigoEstadoSecundario'']'  WHERE CODCERTIFICADO='SVDREXTFECHAWS01';
UPDATE CORE_SERVICIO SET  XPATHCODIGOERRORSECUNDARIO='//*[local-name()=''CodigoEstadoSecundario'']'  WHERE CODCERTIFICADO='SVDRWS01';
UPDATE CORE_SERVICIO SET  XPATHCODIGOERRORSECUNDARIO='//*[local-name()=''CodigoEstadoSecundario'']'  WHERE CODCERTIFICADO='SVDTUWS03';
UPDATE CORE_SERVICIO SET  XPATHCODIGOERRORSECUNDARIO='//*[local-name()=''CodigoEstadoSecundario'']'  WHERE CODCERTIFICADO='SVDLSTTUWS01';
UPDATE CORE_SERVICIO SET  XPATHCODIGOERRORSECUNDARIO='//*[local-name()=''CodigoEstadoSecundario'']'  WHERE CODCERTIFICADO='SVDTNUWS03';
UPDATE CORE_SERVICIO SET  XPATHCODIGOERRORSECUNDARIO='//*[local-name()=''CodigoEstadoSecundario'']'  WHERE CODCERTIFICADO='SVDLSTTNUWS01';
UPDATE CORE_SERVICIO SET  XPATHCODIGOERRORSECUNDARIO='//*[local-name()=''CodigoEstadoSecundario'']'  WHERE CODCERTIFICADO='SVDBECAWS01';
UPDATE CORE_SERVICIO SET  XPATHCODIGOERRORSECUNDARIO='//*[local-name()=''CodigoEstadoSecundario'']'  WHERE CODCERTIFICADO='SVDSEPESITWS02';
UPDATE CORE_SERVICIO SET  XPATHCODIGOERRORSECUNDARIO='//*[local-name()=''CodigoEstadoSecundario'']'  WHERE CODCERTIFICADO='SVDSEPEIACTWS02';
UPDATE CORE_SERVICIO SET  XPATHCODIGOERRORSECUNDARIO='//*[local-name()=''CodigoEstadoSecundario'']'  WHERE CODCERTIFICADO='SVDSEPEIPERWS02';
UPDATE CORE_SERVICIO SET  XPATHCODIGOERRORSECUNDARIO='//*[local-name()=''CodigoEstadoSecundario'']'  WHERE CODCERTIFICADO='SVDSEPEDEMWS01';
UPDATE CORE_SERVICIO SET  XPATHCODIGOERRORSECUNDARIO='//*[local-name()=''CodigoEstadoSecundario'']'  WHERE CODCERTIFICADO='SVDSEPEDEMFECHAWS01';
UPDATE CORE_SERVICIO SET  XPATHCODIGOERRORSECUNDARIO='//*[local-name()=''CodigoEstadoSecundario'']'  WHERE CODCERTIFICADO='SVDCDATWS02';
UPDATE CORE_SERVICIO SET  XPATHCODIGOERRORSECUNDARIO='//*[local-name()=''CodigoEstadoSecundario'']'  WHERE CODCERTIFICADO='SVDCTITWS02';
UPDATE CORE_SERVICIO SET  XPATHCODIGOERRORSECUNDARIO='//*[local-name()=''CodigoEstadoSecundario'']'  WHERE CODCERTIFICADO='SVDCDYGWS02';
UPDATE CORE_SERVICIO SET  XPATHCODIGOERRORSECUNDARIO='//*[local-name()=''CodigoEstadoSecundario'']'  WHERE CODCERTIFICADO='SVDCCSVWS01';
UPDATE CORE_SERVICIO SET  XPATHCODIGOERRORSECUNDARIO='//*[local-name()=''CodigoEstadoSecundario'']'  WHERE CODCERTIFICADO='SVDCBIWS02';
UPDATE CORE_SERVICIO SET  XPATHCODIGOERRORSECUNDARIO='//*[local-name()=''CodigoEstadoSecundario'']'  WHERE CODCERTIFICADO='SVDCDEPENWS01';
UPDATE CORE_SERVICIO SET  XPATHCODIGOERRORSECUNDARIO='//*[local-name()=''CodigoEstadoSecundario'']'  WHERE CODCERTIFICADO='SVDSCCNWS01';
UPDATE CORE_SERVICIO SET  XPATHCODIGOERRORSECUNDARIO='//*[local-name()=''CodigoEstadoSecundario'']'  WHERE CODCERTIFICADO='SVDSCCMWS01';
UPDATE CORE_SERVICIO SET  XPATHCODIGOERRORSECUNDARIO='//*[local-name()=''CodigoEstadoSecundario'']'  WHERE CODCERTIFICADO='SVDSCCDWS01';
UPDATE CORE_SERVICIO SET  XPATHCODIGOERRORSECUNDARIO='//*[local-name()=''CodigoEstadoSecundario'']'  WHERE CODCERTIFICADO='DGSFP0001';
UPDATE CORE_SERVICIO SET  XPATHCODIGOERRORSECUNDARIO='//*[local-name()=''CodigoEstadoSecundario'']'  WHERE CODCERTIFICADO='DGSFP0002';
UPDATE CORE_SERVICIO SET  XPATHCODIGOERRORSECUNDARIO='//*[local-name()=''CodigoEstadoSecundario'']'  WHERE CODCERTIFICADO='DGSFP0003';
UPDATE CORE_SERVICIO SET  XPATHCODIGOERRORSECUNDARIO='//*[local-name()=''CodigoEstadoSecundario'']'  WHERE CODCERTIFICADO='DGSFP0005';
UPDATE CORE_SERVICIO SET  XPATHCODIGOERRORSECUNDARIO='//*[local-name()=''CodigoEstadoSecundario'']'  WHERE CODCERTIFICADO='SVDMAECWS01';
UPDATE CORE_SERVICIO SET  XPATHCODIGOERRORSECUNDARIO='//*[local-name()=''CodigoEstadoSecundario'']'  WHERE CODCERTIFICADO='SVDRESLEGEXWS01';
UPDATE CORE_SERVICIO SET  XPATHCODIGOERRORSECUNDARIO='//*[local-name()=''CodigoEstadoSecundario'']'  WHERE CODCERTIFICADO='SVDNOTLISTWS01';
UPDATE CORE_SERVICIO SET  XPATHCODIGOERRORSECUNDARIO='//*[local-name()=''CodigoEstadoSecundario'']'  WHERE CODCERTIFICADO='SVDNOTSUBWS01';
UPDATE CORE_SERVICIO SET  XPATHCODIGOERRORSECUNDARIO='//*[local-name()=''CodigoEstadoSecundario'']'  WHERE CODCERTIFICADO='SVDNOTCOPSIMWS01';
UPDATE CORE_SERVICIO SET  XPATHCODIGOERRORSECUNDARIO='//*[local-name()=''CodigoEstadoSecundario'']'  WHERE CODCERTIFICADO='SVDNOTSUBADMWS01';
UPDATE CORE_SERVICIO SET  XPATHCODIGOERRORSECUNDARIO='//*[local-name()=''CodigoEstadoSecundario'']'  WHERE CODCERTIFICADO='SVDSCTFNWS01';
UPDATE CORE_SERVICIO SET  XPATHCODIGOERRORSECUNDARIO='//*[local-name()=''CodigoEstadoSecundario'']'  WHERE CODCERTIFICADO='SVDSCDDWS01';
UPDATE CORE_SERVICIO SET  XPATHCODIGOERRORSECUNDARIO='//*[local-name()=''CodigoEstadoSecundario'']'  WHERE CODCERTIFICADO='SVDCCAACPASWS01';
UPDATE CORE_SERVICIO SET  XPATHCODIGOERRORSECUNDARIO='//*[local-name()=''CodigoEstadoSecundario'']'  WHERE CODCERTIFICADO='SVDCCAACPCWS01';
UPDATE CORE_SERVICIO SET  XPATHCODIGOERRORSECUNDARIO='//*[local-name()=''CodigoEstadoSecundario'']'  WHERE CODCERTIFICADO='SVDDGTCONDUCTORWS01';
UPDATE CORE_SERVICIO SET  XPATHCODIGOERRORSECUNDARIO='//*[local-name()=''CodigoEstadoSecundario'']'  WHERE CODCERTIFICADO='SVDDGTVEHICULOWS01';
UPDATE CORE_SERVICIO SET  XPATHCODIGOERRORSECUNDARIO='//*[local-name()=''CodigoEstadoSecundario'']'  WHERE CODCERTIFICADO='SVDIGAECONCESIONWS01';
UPDATE CORE_SERVICIO SET  XPATHCODIGOERRORSECUNDARIO='//*[local-name()=''CodigoEstadoSecundario'']'  WHERE CODCERTIFICADO='SVDIGAEMINIMISWS01';
UPDATE CORE_SERVICIO SET  XPATHCODIGOERRORSECUNDARIO='//*[local-name()=''CodigoEstadoSecundario'']'  WHERE CODCERTIFICADO='SVDIGAEINHABILITACIONWS01';
UPDATE CORE_SERVICIO SET  XPATHCODIGOERRORSECUNDARIO='//*[local-name()=''CodigoEstadoSecundario'']'  WHERE CODCERTIFICADO='SVDVTUWS01';
UPDATE CORE_SERVICIO SET  XPATHCODIGOERRORSECUNDARIO='//*[local-name()=''CodigoEstadoSecundario'']'  WHERE CODCERTIFICADO='SVDVTNUWS01';
UPDATE CORE_SERVICIO SET  XPATHCODIGOERRORSECUNDARIO='//*[local-name()=''CodigoEstadoSecundario'']'  WHERE CODCERTIFICADO='SVDDGOJDESCCOMPLWS01';
UPDATE CORE_SERVICIO SET  XPATHCODIGOERRORSECUNDARIO='//*[local-name()=''CodigoEstadoSecundario'']'  WHERE CODCERTIFICADO='SVDDGOJDESCPARCIALWS01';
UPDATE CORE_SERVICIO SET  XPATHCODIGOERRORSECUNDARIO='//*[local-name()=''CodigoEstadoSecundario'']'  WHERE CODCERTIFICADO='SVDDGOJDESCULTIMAWS01';
UPDATE CORE_SERVICIO SET  XPATHCODIGOERRORSECUNDARIO='//*[local-name()=''CodigoEstadoSecundario'']'  WHERE CODCERTIFICADO='SVDSRSPSBANUALWS01';
UPDATE CORE_SERVICIO SET  XPATHCODIGOERRORSECUNDARIO='//*[local-name()=''CodigoEstadoSecundario'']'  WHERE CODCERTIFICADO='SVDSRSPSBACTUALWS01';
UPDATE CORE_SERVICIO SET  XPATHCODIGOERRORSECUNDARIO='//*[local-name()=''CodigoEstadoSecundario'']'  WHERE CODCERTIFICADO='SVDDGOJALTAWS01';
UPDATE CORE_SERVICIO SET  XPATHCODIGOERRORSECUNDARIO='//*[local-name()=''CodigoEstadoSecundario'']'  WHERE CODCERTIFICADO='SVDDGOJBAJAWS01';
UPDATE CORE_SERVICIO SET  XPATHCODIGOERRORSECUNDARIO='//*[local-name()=''CodigoEstadoSecundario'']'  WHERE CODCERTIFICADO='SVDDGOJMODIFWS01'; 

INSERT INTO CORE_CODIGO_ERROR(CODIGO,DESCRIPCION) VALUES ('0317','El organismo solicitante {0} de la solicitud de respuesta no coincide con el enviado en la petición');


/* 4.3.0 a 4.4.0 */
UPDATE CORE_PARAMETRO_CONFIGURACION SET VALOR='4.4.0' WHERE NOMBRE='version.datamodel.scsp';   
INSERT INTO CORE_PARAMETRO_CONFIGURACION (NOMBRE,DESCRIPCION,VALOR) VALUES ('task.polling.size','Número de peticiones máximo a ser tratadas por ciclo de polling','50'); 
UPDATE CORE_SERVICIO SET DESCRIPCION = 'Estar al corriente de obligaciones tributarias para contratación con las administraciones públicas' WHERE CODCERTIFICADO = 'ECOT101I';
DELETE FROM CORE_PARAMETRO_CONFIGURACION WHERE NOMBRE='core_log.enabled';

/* 4.6.0 a 4.7.0 */
UPDATE CORE_PARAMETRO_CONFIGURACION SET VALOR='4.6.0' WHERE NOMBRE='version.datamodel.scsp';   

/* 4.7.0 a 4.8.0 */
UPDATE CORE_PARAMETRO_CONFIGURACION SET VALOR='4.8.0' WHERE NOMBRE='version.datamodel.scsp';  
UPDATE CORE_EMISOR_CERTIFICADO SET FECHAALTA = SYSDATE  WHERE FECHAALTA IS NULL;

/* 4.8.0 a 4.16.0 */
UPDATE CORE_PARAMETRO_CONFIGURACION SET VALOR='4.16.0' where NOMBRE='version.datamodel.scsp'; 

/* 4.16.0 a 4.19.0 */

/* NO SCSP */
UPDATE EMS_SERVEI SET XSD_ACTIVA=0 WHERE XSD_ACTIVA IS NULL;