#!/bin/bash

set -o nounset
set -o errexit

#### Description: Checks environment variables
#### Written by: Guillermo de Ignacio - gdeignacio@fundaciobit.org on 04-2021

###################################
###   Test environment values   ###
###################################

unameOut="$(uname -s)"
case "${unameOut}" in
    Linux*)     machine=Linux;;
    Darwin*)    machine=Mac;;
    CYGWIN*)    machine=Cygwin;;
    MINGW*)     machine=MinGw;;
    *)          machine="UNKNOWN:${unameOut}"
esac

echo "Your SO is ${machine} according uname=${unameOut}"

linuxMode=0
# Assign mode 1 if so is linux or mac, 0 otherwise
if [[ ${machine} == "Linux" || ${machine} == "Mac" ]]; then
    linuxMode=1
fi

DOCKER_COMPOSE=/dev/null
if [[ linuxMode -eq 1 ]]; then
    DOCKER_COMPOSE=$(which docker-compose)
    echo ""
    echo "Docker compose at $DOCKER_COMPOSE"
    echo ""
else
    echo ""
    echo "Docker compose unavailable"
    echo ""
fi

PROJECT_PATH="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && cd .. && pwd )"
echo "Project path at $PROJECT_PATH"
echo ""
echo "[$(date +"%Y-%m-%d %T")] Testing env..."
echo ""

source $PROJECT_PATH/bin/_app__loadenv.sh


