#!/bin/bash
#### Description: Checks Java and Maven version
#### Written by: Guillermo de Ignacio - gdeignacio@fundaciobit.org on 04-2021

###################################
###   Test environment values   ###
###################################

DOCKER_COMPOSE=$(which docker-compose)
echo ""
echo "Docker compose at $DOCKER_COMPOSE"
echo ""
####################

PROJECT_PATH="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && cd .. && pwd )"
echo "Project path at $PROJECT_PATH"
echo ""
echo "[$(date +"%Y-%m-%d %T")] testing env..."
echo ""

source $PROJECT_PATH/bin/loadenv

echo ""
echo Checking Java version
echo ""
java -version
echo ""
echo Checking Maven version
echo ""
mvn -version
echo ""
echo Checking Maven settings
mvn help:effective-settings --settings $PROJECT_PATH/builds/maven-dist/maven/conf/settings.xml
echo ""